const path = require('path')
const webpack = require('webpack')
const validate = require('webpack-validator')
const CleanWebpackPlugin = require('clean-webpack-plugin')
const HtmlWebpackPlugin = require('html-webpack-plugin')
const ExtractTextPlugin = require('extract-text-webpack-plugin')
const Merge = require('webpack-merge')
const OpenBrowserPlugin = require('open-browser-webpack-plugin')
